package com.asm;

/**
 * @author sad
 */
public enum Architecture {
    ARCH_8086, ARCH_186,ARCH_286,ARCH_386,ARCH_486,ARCH_PENT,ARCH_FPU, ARCH_PRIV,ARCH_SB,ARCH_SM,ARCH_LOCK,ARCH_ND,ARCH_PROT,ARCH_BND,ARCH_AR0,ARCH_SD,ARCH_SIZE,ARCH_NOHLE,ARCH_SW,ARCH_SM2,ARCH_OPT,ARCH_AR2
}
